name: test
on: push
jobs:
  ci:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          powershell -ExecutionPolicy ByPass -File "windowssetup.ps1"
        shell: powershell
