name: windows_setup_test

on: push

jobs:
  CI:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run_setup_windows
        run: |
          powershell -NoProfile -ExecutionPolicy ByPass ./windowssetup.ps1
        shell: pwsh